name: Push to feature branch

on:
  push:
    branches:
      - "*"
      - "!main"

env:
  TF_LOG: INFO
  TF_INPUT: false

jobs:
  check-code:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.7.4"

      - name: Terraform Init
        id: init
        run: terraform init -backend-config="access_key=${{ secrets.AWS_ACCESS_KEY_ID_TERRAFORM }}" -backend-config="secret_key=${{ secrets.AWS_SECRET_ACCESS_KEY_TERRAFORM }}"
        working-directory: ./terraform

      - name: Terraform Format
        id: fmt
        run: terraform fmt -check -backend-config="access_key=${{ secrets.AWS_ACCESS_KEY_ID_TERRAFORM }}" -backend-config="secret_key=${{ secrets.AWS_SECRET_ACCESS_KEY_TERRAFORM }}"
        working-directory: ./terraform

      - name: Terraform Validate
        id: validate
        # Run even if formatting fails
        if: success() || failure()
        run: terraform validate -no-color -backend-config="access_key=${{ secrets.AWS_ACCESS_KEY_ID_TERRAFORM }}" -backend-config="secret_key=${{ secrets.AWS_SECRET_ACCESS_KEY_TERRAFORM }}"
        working-directory: ./terraform
